"""
pprojekt_2.py: druhý projekt do Engeto Online Python Akademie

author: Anastasija Kozlovska
email: kozlovska.st@gmail.com
discord: anastasia0163

"""
import random

print("Welcome to the game Bulls&Cows!")
print("Find the numbers generated by the computer: ")
print("_ _ _ _")

def secret_number():
    '''
    generace 4 náhodných čísel, nesmí být 0 na začátku
    '''
    first_digit = random.choice("123456789")
    other_digits = "".join(random.sample(list(set("0123456789") - {first_digit}), 3))
    computer_number = first_digit + other_digits
    return computer_number

# žádáme uživatele napsat neopakující se čísla
def input_number():
    while True:
        user_nums = input("Put 4 non-repeating numbers( 'q' for quit game): ")

        if len(user_nums) != 4 or not user_nums.isdigit():
            print("Valid input. Please try again.")
            continue
        elif len(set(user_nums)) != len(user_nums):
            print("Numbers are repeated. Please try again.")
            continue
        elif user_nums == "q":
            print("The end.")
            quit()
        else:
            break
    return user_nums
        

# počítáme bulls a cows v input 
def count_bulls_and_cows(user_nums, secret_number):
    bulls, cows = 0, 0

    for i, num in enumerate(user_nums):
        if num in secret_number:
            if num == secret_number[i]:
                bulls += 1
            else:
                cows += 1
    return bulls, cows

# vypisování hry do konzole
def play_game():
    computer_number = secret_number()

    while True:
        user_nums = input_number() 
        bulls, cows = count_bulls_and_cows(user_nums, computer_number)

        print(f"Bulls: {bulls}, Cows: {cows}")
    
        if bulls == 4:
            print("Congratulations!!! You guessed the number.")
            break
        

def new_game():
    while True:
        print("Do you want to play again?")
        next_play = input("For 'Yes' print Y, for 'No' print N: ")
        if next_play.lower() not in {"y", "n"}:
            print("I dont understand. Please write Y or N")
        elif next_play.lower() == "n":
            break
        else:
            play_game() 


if __name__ == "__main__":
    print("Welcome to the game Bulls & Cows!")
    print("Find the numbers generated by the computer.")
    play_game()
    new_game()


            

